//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthernClinique
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admission
    {
        public int IDAdmission { get; set; }
        public bool chirurgie_programmee { get; set; }
        public System.DateTime date_admission { get; set; }
        public Nullable<System.DateTime> date_chirurgie { get; set; }
        public Nullable<System.DateTime> date_du_congé { get; set; }
        public bool televiseur { get; set; }
        public bool telephone { get; set; }
        public int NSS { get; set; }
        public int Numero_lit { get; set; }
        public int IDMedecin { get; set; }
    
        public virtual Lit Lit { get; set; }
        public virtual Medecin Medecin { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
