//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthernClinique
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminLitMedPatient
    {
        public int NoAdmission { get; set; }
        public int NoLit { get; set; }
        public System.DateTime Admission { get; set; }
        public Nullable<System.DateTime> Congé { get; set; }
        public bool Status_du_lit { get; set; }
        public string Médecin { get; set; }
        public string Prénom_Patient { get; set; }
        public string Nom_Patient { get; set; }
    }
}
