//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthernClinique
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Northern_Lights_HospitalEntities1 : DbContext
    {
        public Northern_Lights_HospitalEntities1()
            : base("name=Northern_Lights_HospitalEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admission> Admission { get; set; }
        public virtual DbSet<Assurance> Assurance { get; set; }
        public virtual DbSet<Departement> Departement { get; set; }
        public virtual DbSet<Lit> Lit { get; set; }
        public virtual DbSet<Medecin> Medecin { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<Type_Lit> Type_Lit { get; set; }
    }
}
